# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kukuh Prabowo
email: kukuhpro@gmail.com
description: > # "baseurl:"
  My name is Kukuh Prabowo, I'am a software engineer who focus on web and android application.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kukuhpro.github.io" # the base hostname & protocol for your site
twitter_username: kukuhprb
github_username:  kukuhpro

# Meta Setting
meta-title: kukuhpro.github.io
meta-description: Fell new way of life for being programmer.
meta-image: /assets/img/no-picture.png

# Build settings
markdown: kramdown
include: [assets]
